# -----------------------------
# Application Configuration
# -----------------------------
spring.application.name=lms-b

# -----------------------------
# Datasource Configuration
# -----------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/lms_db
spring.datasource.username=root
spring.datasource.password=Mammu@1412
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# -----------------------------
# JPA / Hibernate Configuration
# -----------------------------
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect+
logging.level.org.springframework.security=DEBUG
# -----------------------------
# Liquibase Configuration
# -----------------------------
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
#spring.liquibase.contexts=development,production
spring.liquibase.default-schema=lms_db
spring.liquibase.drop-first=false

#logging.level.liquibase=DEBUG
#logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG

# -----------------------------
# Server Configuration
# -----------------------------
server.port=9090

spring.security.user.name=admin
spring.security.user.password=admin123


# ===============================
# MAIL CONFIGURATION
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shivashankar.damidi@gmail.com
spring.mail.password=cjboapljipidamgw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional (but helpful)
spring.mail.default-encoding=UTF-8
spring.mail.test-connection=false

springdoc.swagger-ui.persistAuthorization=true

strapi.url=http://localhost:1337
strapi.api.token=e903c1334939ba5bb846370c5caccfcc5b9f09c12118ff69eeb67efea04f7a4e95d0126c4bdd4d8414f9509b4397c459f4e41aab2896dad19c4da6af38d8fdb17f6fd7fb3719a143ec5c7a1afe5f9a17446d25e03a2ad8357406e7c79ebe1b6b62c8a2b8c5a621ed50a8ef937e32b759faa095f7d2e87063623a0a4e3bb7d516
# File size limits
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB